In [6]:
#1.Debug the given code
import pandas as pd



# Convert to numeric, force errors to NaN

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
       'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)


#d['Feature1'] = df['Feature1'].astype(int)  # Error: Cannot convert 'Thirty' to int

df['Feature1'] = pd.to_numeric(df['Feature1'], errors='coerce').astype('Int64') 

print(df)



   Feature1  Feature2
0        10       5.5
1        20       6.7
2       NaN       8.9


In [9]:
#2.
import pandas as pd

data1 = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df1 = pd.DataFrame(data1)
mean_value = df1.mean()
df1.fillna(mean_value)  # Error: fillna() does not modify in place

print(df1)


     A    B
0  1.0  4.0
1  2.0  NaN
2  NaN  6.0


In [13]:
#3.
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5])  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit([X],[y])


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50])  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform([data])

print(scaled_data)


[[0. 0. 0. 0. 0.]]


In [16]:
#5.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric

model = LogisticRegression()
model.fit(X, y)


C:\Anaconda\anaconda3\envs\aiml\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
#6.import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df['Category'].values.reshape(-1,1)) # Error: Data should be reshaped
print(encoded)


  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 0)	1.0


In [28]:
#6.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0 , 1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [39]:
#7.
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)

print(y_train_encoded)  
model = LogisticRegression()
model.fit(X_train, y_train_encoded)


[1 0 1]


C:\Anaconda\anaconda3\envs\aiml\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [38]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

# Creating a dataset with missing values
#X_train = np.array([[1, 2], [3, np.nan], [5, 6]])

X_train = np.array([[1, 2],
                    [3, np.nan],
                    [5, 6]])

# Replace NaNs with column means
imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)

print(X_train_imputed)

y_train = np.array([10, 20, 30])

model = LinearRegression()
#model.fit(X_train, y_train)
model.fit(X_train_imputed, y_train) 


[[1. 2.]
 [3. 4.]
 [5. 6.]]


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [40]:
#9.
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

model = DecisionTreeClassifier()
model.fit(X_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [42]:
#10.
from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

model = SVC()
model.fit(X_train, y_train)
print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference


[0]


C:\Anaconda\anaconda3\envs\aiml\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
